/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GraphicsEngineJNI */

#ifndef _Included_GraphicsEngineJNI
#define _Included_GraphicsEngineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GraphicsEngineJNI
 * Method:    infoMsg
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_GraphicsEngineJNI_infoMsg
  (JNIEnv *, jobject, jstring);

/*
 * Class:     GraphicsEngineJNI
 * Method:    createApp
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_GraphicsEngineJNI_createApp
  (JNIEnv *, jobject, jstring);

/*
 * Class:     GraphicsEngineJNI
 * Method:    updateApp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_GraphicsEngineJNI_updateApp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GraphicsEngineJNI
 * Method:    destroyApp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_GraphicsEngineJNI_destroyApp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GraphicsEngineJNI
 * Method:    getRunLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_GraphicsEngineJNI_getRunLevel
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
